const password = process.env.ADMIN_PASSWORD;
const apiKey = process.env.API_KEY;
const db = require('mongodb');
const mongoSanitize = require('express-mongo-sanitize');
const sanitize = mongoSanitize();
const express = require('express');
const app = express();
app.use(express.json());
app.use(sanitize);
db.collection.find({user: sanitize(req.body.username)});
const secret = process.env.SECRET_KEY;